#cloud-config
#Based on https://gist.github.com/vtrifonov-esfiddle/068dd818b5f929709b688c805c507e65
groups:
  - docker
users:
  - default
  # the docker service account
  - name: docker-service
    groups: docker
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  # install docker-compose following the guide: https://docs.docker.com/compose/install/
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  # Mount volume, WARNING! hardcoded id
  - sudo echo "/dev/disk/by-id/scsi-0HC_Volume_17241376 /mnt/zomboid-data ext4 discard,nofail,defaults 0 0" >> /etc/fstab
  # Fetch files
  - sudo apt-get -y install git
  - sudo git clone https://github.com/chumbucketorg/cb-zomboid /root/cb-zomboid
  # Retrieve docker image
  - sudo docker pull vmednis/zomboid
  # Set-up zomboid service
  - sudo cp /root/cb-zomboid/zomboid.service /etc/systemd/system/
  - sudo systemctl enable zomboid
power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose